server:
  port: 8081

spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/zodiac_mirror #connect to local mysql
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# Specify the DBMS  
  jpa:
    database: MYSQL  
# Show or not log for each sql query  
    show-sql: true  
# Hibernate ddl auto (create, create-drop, update)  
    hibernate:
      ddl-auto: update
# stripped before adding them to the entity manager
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
